apiVersion: batch/v1
kind: Job
metadata:
  name: node-disk-cleanup
spec:
  ttlSecondsAfterFinished: 60   # Job complete ஆன 60 sec-கு பிறகு auto delete
  template:
    spec:
      restartPolicy: Never
      hostPID: true
      containers:
      - name: cleanup
        image: alpine:latest
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          echo "===== Pod usage ====="
          kubectl top pods -A --sort-by=ephemeral-storage || true

          echo "===== CRI containers ====="
          crictl ps -a || true

          echo "===== CRI images ====="
          crictl images || true

          echo "===== Containerd disk usage ====="
          du -sh /var/lib/containerd/* || true

          echo "===== Docker cleanup ====="
          docker system df || true

          echo "===== CRI image prune ====="
          crictl rmi --prune || true

          echo "===== Journal cleanup ====="
          journalctl --vacuum-time=1d || true

          echo "===== Deleted open files ====="
          lsof | grep deleted || true

          echo "===== Cleanup completed ====="
        volumeMounts:
        - name: containerd
          mountPath: /var/lib/containerd
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: containerd
        hostPath:
          path: /var/lib/containerd
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock

