apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-httpd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: container2
        image: httpd:__HTTPD_VERSION__
